name: torchlinops
channels:
  - frankong
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  # Cupy stuff
  - cupy=12.1.0
  #- cudnn>=8.8.0.121
  - cutensor>=1.7.0.1
  - nccl>=2.15.5.1
  # Jupyter/plotting
  - jupyter
  - jupyterlab
  - jupyterlab_pygments
  # - jupyterlab_vim # broken
  # - jupyterlab_widgets # broken
  #
  - matplotlib
  - nodejs # for jupyter extensions
  - numpy=1.22  #fix version to ignore sigpy errors
  - python=3.10
  - pytest
  - pytorch=2.1
  - pytorch-cuda=12.1
  - PyWavelets
  - scipy
  - torchvision
  - torchaudio
  - tqdm
  - pyyaml
  - pip
  - pip:
     - easydict
     - einops
     - gdown
     - graphviz
     - h5py
     # Jupyterlab extensions
     # - jupyterlab-vimrc
     - mat73 # loading matlab v7.3 format files
     - multipledispatch
     - multimethod # TODO: deprecate multipledispatch
     - pymapvbvd # Loading Siemens twix files
     - pytorch_memlab
     - pyyaml
     - ruff          # Better linting in Rust
     - sigpy==0.1.25 # here bc of python 3.10 I think
     - tensorboard
     - torchgeometry
     - torchkbnufft
     - torchview
     - tyro
     - wandb
     - wget
     - wonderwords
     #- git+ssh://git@github.com/nishi951/pytorch-flows.git@main # Unnecessary now
