[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "torch-named-linops"
description = "A flexible linear operator abstraction in pytorch."
version = "0.2.0"
authors = [
    { name = "Mark Nishimura", email = "markn1@stanford.edu" }
]
dependencies = [
    "torch>=2.1",
    "torchvision",
    "torchaudio",

    # NUFFT
    # "finufft>=2.2.0",
    # "cufinufft>=2.2.0",

    # Misc utilities
    "einops",
    "tqdm",
    "pyyaml",

    # TODO: remove these dependencies
    # "sigpy == 0.1.25", # Good nufft, other mri utils
    # "numpy == 1.22",   # Here because sigpy is legacy
    # "scipy",           # also here for sigpy
    # "torchkbnufft",    # Also a good nufft
]
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
test = [
    "gdown", # Downloading test files
    "marimo", # Better notebooks
    "matplotlib", # Visualization
    # "pytorch_pfn_extras", # Mempool sharing between cupy and pytorch
    # Sigpy for various utils
    # Other versions locked for compatibility (may change soon)
    # "sigpy == 0.1.25",
    # "numpy == 1.22",
    # "scipy",

]
cuda11 = [
    "cupy-cuda11x<13.0", # Avoid cublas error
    "cutensor-cu11",
    #"nvidia-nccl-cu11", # install via conda or cupy install command
    # ``` sh
    # python -m cupyx.tools.install_library --library nccl --cuda 11.x
    # ```

]
cuda12 = [
    "cupy-cuda12x<13.0", # Avoid cublas error
    "cutensor-cu12",
    #"nvidia-nccl-cu12", # install via conda or cupy install command
    # ``` sh
    # python -m cupyx.tools.install_library --library nccl --cuda 12.x
    # ```
]
dev = [
    "pytest", # Unit tests
    "pytest-cov", # Code coverage
    "ruff", # Linting
    "pre-commit", # pre-commit hooks
    "sphinx", # Build system
    "furo",   # Theme
]
all = ["torch-mri-linops[test, dev]"]

# TODO: Deprecate this once the other packages are established
[tool.setuptools.package-dir]
torchlinops = "src/torchlinops"
# igrog = "libraries/igrog/src/igrog"
# mr_recon = "libraries/igrog/mr_recon/src/mr_recon"
# optim_mrf = "libraries/optimized-mrf/src/optim_mrf"
# mr_sim = "libraries/mr_sim/src/mr_sim"


[tool.ruff]
target-version = "py310"
extend-exclude = ["**/libraries/*"]

[tool.ruff.lint]
ignore = [
    "F403", # from ___ import *
    "F401", # unused imports
]
exclude = ["**/tests/**"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
-ra -q \
-m 'not slow and not gpu and not plot' \
--cov-report html
"""
# --ignore libraries --ignore notebooks"
filterwarnings = [
    "ignore::DeprecationWarning:sigpy.*",
    "ignore::DeprecationWarning:cupy.*",
]
markers = [
    "slow: tests that are slow (deselect with '-m \"not slow\"')",
    "big: tests that require large memory (cpu or gpu)",
    "gpu: tests that require a gpu",
    "plot: tests that involve plotting",
]

[tool.coverage.run]
omit = ["*/test[s?]/*"] # Both */test/* and */tests/*
