[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "torchlinops"
description = "A library for MRI reconstruction with a torch linear operator abstraction."
version = "0.1.8"
authors = [
    { name = "Mark Nishimura", email = "markn1@stanford.edu" }
]
dependencies = [
    # NUFFT
    "finufft>=2.2.0",
    # Sigpy for various utils
    # Other versions locked for compatibility (may change soon)
    "sigpy == 0.1.25",
    "numpy == 1.22",
    "scipy",
    "torchkbnufft",
    # User should install these themselves
    # "pytorch >= 2.1",
    # "torchvision",
    # "torchaudio,"
    # Misc utilities
    "einops",
    "tqdm",
    "pyyaml",
]
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
cuda12 = [
    "cufinufft>=2.2.0",
    # Versions compatible with sigpy
    "cupy-cuda12x<13.0", # Avoid cublas error
    "cutensor-cu12",
    #"nvidia-nccl-cu12", # install via conda or cupy install command
    # ``` sh
    # python -m cupyx.tools.install_library --library nccl --cuda 12.x
    # ```
]
cuda11 = [
    "cufinufft>=2.2.0",
    # Versions compatible with sigpy
    "cupy-cuda11x<13.0", # Avoid cublas error
    "cutensor-cu11",
    #"nvidia-nccl-cu11", # install via conda or cupy install command
    # ``` sh
    # python -m cupyx.tools.install_library --library nccl --cuda 11.x
    # ```
]
dev = [
    "pytest", # Unit tests
    "ruff", # Linting
    "pre-commit",
    "gdown", # Downloading test files
    "marimo", # Better notebooks
    "matplotlib", # Visualization
    "pytorch_pfn_extras", # Mempool sharing between cupy and pytorch
]

[tool.ruff]
target-version = "py310"
extend-exclude = ["**/libraries/*"]

[tool.ruff.lint]
ignore = [
    "F403", # from ___ import *
    "F401", # unused imports
]
exclude = ["tests"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
-ra -q \
-m 'not slow and not gpu and not plot' \
--ignore-glob **/mri/_grid/backends/_kgrog/tests/* \
--ignore-glob **/mri/app/tests/* \
--ignore libraries \
--ignore notebooks \
--ignore-glob **/mri/data/* \
--ignore-glob **/mri/sim/*
"""
# --ignore libraries --ignore notebooks"
filterwarnings = [
    "ignore::DeprecationWarning:sigpy.*",
    "ignore::DeprecationWarning:cupy.*",
]
markers = [
    "slow: tests that are slow (deselect with '-m \"not slow\"')",
    "big: tests that require large memory (cpu or gpu)",
    "gpu: tests that require a gpu",
    "plot: tests that involve plotting",
]
